// Generated by CoffeeScript 1.10.0
(function() {
  exports.bubbleProp = (function() {
    var cache;
    cache = {};
    return function(prop, name) {
      var cached, handler;
      if (prop) {
        cached = cache[name];
        if (cached) {
          this.stopListening(cached.prop, 'all', cached.handler);
        }
        handler = this._getEventBubblingHandler(name);
        this.listenTo(prop, 'all', handler);
        return cache[name] = {
          prop: prop,
          handler: handler
        };
      }
    };
  })();

}).call(this);
